# Example GitHub Actions workflow for building backend image, pushing to ECR,
# building frontend, syncing to S3, and invalidating CloudFront.
# Save as .github/workflows/deploy.yml or in this repo for reference.

name: Deploy examapp

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and push backend image
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/examapp-backend:latest
          (cd backend && docker build -t examapp-backend .)
          docker tag examapp-backend "$IMAGE"
          docker push "$IMAGE"

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Sync frontend to S3
        env:
          FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}
        run: |
          aws s3 sync frontend/dist s3://$FRONTEND_BUCKET/ --delete

      - name: Invalidate CloudFront
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

# Notes:
# - Configure secrets in GitHub: AWS_ACCOUNT_ID, AWS_ROLE_TO_ASSUME, FRONTEND_BUCKET, CLOUDFRONT_DISTRIBUTION_ID
# - The workflow assumes the role specified by AWS_ROLE_TO_ASSUME has permissions to push to ECR, manage S3, CloudFront, and deploy ECS/task updates via Terraform or other mechanisms.
