/**
 * Maps exact technology strings (as used in lab.technologies[]) to their S3 icon keys.
 * Keys are normalised flat paths — no category subdirectory.
 * Icons are served from the examapp-images-* S3 bucket via /images/presigned.
 * Add entries here as new services appear in skill labs.
 */
export const CLOUD_ICON_KEYS: Record<string, string> = {
  // ── AWS ─────────────────────────────────────────────────────────────────────
  'EC2': 'icons/aws/ec2.svg',
  'ECS': 'icons/aws/elastic-container-service.svg',
  'ECR': 'icons/aws/elastic-container-registry.svg',
  'EBS': 'icons/aws/elastic-block-store.svg',
  'EFS': 'icons/aws/efs.svg',
  'ELB': 'icons/aws/elastic-load-balancing.svg',
  'ALB': 'icons/aws/elastic-load-balancing.svg',
  'EMR': 'icons/aws/emr.svg',
  'RDS': 'icons/aws/rds.svg',
  'S3': 'icons/aws/simple-storage-service.svg',
  'SQS': 'icons/aws/simple-queue-service.svg',
  'SNS': 'icons/aws/simple-notification-service.svg',
  // 'STS': no dedicated icon in this set
  'VPC': 'icons/aws/virtual-private-cloud.svg',
  'WAF': 'icons/aws/waf.svg',
  'IAM': 'icons/aws/identity-and-access-management.svg',
  'KMS': 'icons/aws/key-management-service.svg',
  'DAX': 'icons/aws/dynamodb.svg',
  'DNS': 'icons/aws/route-53.svg',

  'Lambda': 'icons/aws/lambda.svg',
  'DynamoDB': 'icons/aws/dynamodb.svg',
  'Aurora': 'icons/aws/aurora.svg',
  'ElastiCache': 'icons/aws/elasticache.svg',
  'CloudWatch': 'icons/aws/cloudwatch.svg',
  'CloudWatch Logs': 'icons/aws/cloudwatch.svg',
  'CloudFront': 'icons/aws/cloudfront.svg',
  'CloudTrail': 'icons/aws/cloudtrail.svg',
  'CloudFormation': 'icons/aws/cloudformation.svg',
  'EventBridge': 'icons/aws/eventbridge.svg',
  'GuardDuty': 'icons/aws/guardduty.svg',
  'Cognito': 'icons/aws/cognito.svg',

  'Route 53': 'icons/aws/route-53.svg',
  'Auto Scaling': 'icons/aws/auto-scaling.svg',
  'Secrets Manager': 'icons/aws/secrets-manager.svg',
  'Systems Manager': 'icons/aws/systems-manager.svg',
  'Directory Service': 'icons/aws/directory-service.svg',

  'CodeBuild': 'icons/aws/codebuild.svg',
  'CodePipeline': 'icons/aws/codepipeline.svg',

  'AWS IAM': 'icons/aws/identity-and-access-management.svg',
  'AWS Lambda': 'icons/aws/lambda.svg',
  'AWS Glue': 'icons/aws/glue.svg',
  'AWS Step Functions': 'icons/aws/step-functions.svg',
  'AWS Lake Formation': 'icons/aws/lake-formation.svg',
  'AWS CodePipeline': 'icons/aws/codepipeline.svg',

  'Amazon Athena': 'icons/aws/athena.svg',
  'Amazon Bedrock': 'icons/aws/sagemaker.svg',  // no dedicated Bedrock icon in this set
  'Amazon DAX': 'icons/aws/dynamodb.svg',
  'Amazon DynamoDB': 'icons/aws/dynamodb.svg',
  'Amazon EMR': 'icons/aws/emr.svg',
  'Amazon MSK': 'icons/aws/managed-streaming-for-apache-kafka.svg',
  'Amazon Redshift': 'icons/aws/redshift.svg',
  'Amazon SageMaker': 'icons/aws/sagemaker.svg',
  'Amazon Textract': 'icons/aws/textract.svg',

  'Bedrock Agents': 'icons/aws/sagemaker.svg',
  'Bedrock Knowledge Bases': 'icons/aws/sagemaker.svg',

  'Kinesis Data Streams': 'icons/aws/kinesis-data-streams.svg',
  'Kinesis Firehose': 'icons/aws/kinesis-firehose.svg',
  'OpenSearch Serverless': 'icons/aws/opensearch-service.svg',
  'Step Functions': 'icons/aws/step-functions.svg',

  'Security Groups': 'icons/aws/waf.svg',
  'Network ACLs': 'icons/aws/virtual-private-cloud.svg',
  'Internet Gateway': 'icons/aws/virtual-private-cloud.svg',
  'NAT Gateway': 'icons/aws/virtual-private-cloud.svg',
  'Target Groups': 'icons/aws/elastic-load-balancing.svg',

  // ── Terraform / general infra ────────────────────────────────────────────────
  // No cloud-specific icon — intentionally omitted (renders as text-only chip)

  // ── Azure ────────────────────────────────────────────────────────────────────
  'Azure AI Foundry':                'icons/azure/ai-studio.svg',
  'Azure AI Language':               'icons/azure/cognitive-services.svg',
  'Azure AI Speech':                 'icons/azure/speech-services.svg',
  'Azure AI Vision':                 'icons/azure/computer-vision.svg',
  'Azure AI Document Intelligence':  'icons/azure/form-recognizers.svg',
  'Azure AI Custom Vision':          'icons/azure/custom-vision.svg',
  'Azure AI Content Understanding':  'icons/azure/cognitive-services.svg',
  'Azure Cognitive Services':        'icons/azure/cognitive-services.svg',
  'Azure Machine Learning':          'icons/azure/machine-learning.svg',
  'Azure ML Pipelines':              'icons/azure/machine-learning.svg',
  'Azure ML Feature Store':          'icons/azure/machine-learning.svg',
  'Azure ML Model Registry':         'icons/azure/machine-learning.svg',
  'Managed Online Endpoint':         'icons/azure/machine-learning.svg',
  'Batch Endpoint':                  'icons/azure/machine-learning.svg',
  'AmlCompute':                      'icons/azure/machine-learning.svg',
  'Model Monitoring':                'icons/azure/machine-learning.svg',
  'Responsible AI':                  'icons/azure/machine-learning.svg',
  'Responsible AI Dashboard':        'icons/azure/machine-learning.svg',
  'Azure OpenAI':                    'icons/azure/azure-openai.svg',
  'GPT-4o':                          'icons/azure/azure-openai.svg',
  'DALL-E':                          'icons/azure/azure-openai.svg',
  'Whisper':                         'icons/azure/azure-openai.svg',
  'Phi':                             'icons/azure/azure-openai.svg',
  'Prompt Shield':                   'icons/azure/content-moderators.svg',
  'Azure Key Vault':                 'icons/azure/key-vaults.svg',
  'Azure Storage':                   'icons/azure/storage-accounts.svg',
  'Azure Data Lake':                 'icons/azure/data-lake-storage-gen1.svg',
  'Microsoft Entra ID':              'icons/azure/entra-id-protection.svg',
  'Managed Identity':                'icons/azure/managed-identities.svg',
  'Azure RBAC':                      'icons/azure/identity-governance.svg',
  'Microsoft Sentinel':              'icons/azure/azure-sentinel.svg',
  'Microsoft Purview':               'icons/azure/compliance-center.svg',
  'Azure Monitor':                   'icons/azure/monitor.svg',
  'Log Analytics':                   'icons/azure/log-analytics-workspaces.svg',
  'Diagnostic Settings':             'icons/azure/diagnostics-settings.svg',
  'Azure DNS':                       'icons/azure/dns-zones.svg',
  'Azure Private Endpoint':          'icons/azure/private-endpoints.svg',
  'Azure CLI':                       'icons/azure/powershell.svg',
  'KQL':                             'icons/azure/log-analytics-workspaces.svg',
  'Sensitivity Labels':              'icons/azure/information-protection.svg',
  'YAML':                            'icons/azure/azure-devops.svg',

  // ── GCP ──────────────────────────────────────────────────────────────────────
  'Vertex AI':                       'icons/gcp/vertex-ai.svg',
  'Vertex AI Search':                'icons/gcp/vertex-ai.svg',
  'Vertex AI Pipelines':             'icons/gcp/vertex-ai.svg',
  'Vertex AI Feature Store':         'icons/gcp/vertex-ai.svg',
  'Vertex AI Model Monitoring':      'icons/gcp/vertex-ai.svg',
  'Vertex AI Vizier':                'icons/gcp/vertex-ai.svg',
  'Vertex Explainable AI':           'icons/gcp/vertex-ai.svg',
  'Vertex AI Endpoints':             'icons/gcp/vertex-ai.svg',
  'Vertex AI Model Cards':           'icons/gcp/vertex-ai.svg',
  'Vertex AI Model Registry':        'icons/gcp/vertex-ai.svg',
  'Gemini':                          'icons/gcp/ai-platform.svg',
  'Gemma':                           'icons/gcp/ai-platform.svg',
  'Imagen':                          'icons/gcp/ai-platform.svg',
  'Veo':                             'icons/gcp/ai-platform.svg',
  'Chirp':                           'icons/gcp/ai-platform.svg',
  'Agent Builder':                   'icons/gcp/dialogflow-cx.svg',
  'Agentspace':                      'icons/gcp/dialogflow-cx.svg',
  'Model Armor':                     'icons/gcp/security.svg',
  'BigQuery':                        'icons/gcp/bigquery.svg',
  'BigQuery ML':                     'icons/gcp/bigquery.svg',
  'BigQuery Data Transfer Service':  'icons/gcp/data-transfer.svg',
  'Cloud Storage':                   'icons/gcp/cloud-storage.svg',
  'Storage Transfer Service':        'icons/gcp/transfer.svg',
  'Cloud Build':                     'icons/gcp/cloud-build.svg',
  'Cloud Composer':                  'icons/gcp/cloud-composer.svg',
  'Cloud Functions':                 'icons/gcp/cloud-functions.svg',
  'Cloud Run':                       'icons/gcp/cloud-run.svg',
  'Cloud SQL':                       'icons/gcp/cloud-sql.svg',
  'Cloud KMS':                       'icons/gcp/key-management-service.svg',
  'Cloud Logging':                   'icons/gcp/cloud-logging.svg',
  'Cloud Monitoring':                'icons/gcp/cloud-monitoring.svg',
  'Cloud Spanner':                   'icons/gcp/cloud-spanner.svg',
  'Dataflow':                        'icons/gcp/dataflow.svg',
  'Dataproc':                        'icons/gcp/dataproc.svg',
  'Dataplex':                        'icons/gcp/dataplex.svg',
  'Pub/Sub':                         'icons/gcp/pubsub.svg',
  'IAM':                             'icons/gcp/identity-and-access-management.svg',
  'Looker':                          'icons/gcp/looker.svg',
  'Workspace':                       'icons/gcp/google-kubernetes-engine.svg',
  'NotebookLM':                      'icons/gcp/ai-platform.svg',
  'Airflow':                         'icons/gcp/cloud-composer.svg',
  'TFX':                             'icons/gcp/tensorflow-enterprise.svg',
  'TensorFlow Data Validation':      'icons/gcp/tensorflow-enterprise.svg',
  'KFP':                             'icons/gcp/vertex-ai.svg',
  'SQL':                             'icons/gcp/cloud-sql.svg',
  'Python':                          'icons/gcp/cloud-code.svg',
}
