name: Frontend Deploy

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'frontend/**'

env:
  AWS_REGION: eu-west-1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build frontend
        env:
            VITE_AUTH_MODE: cognito
            VITE_AUTH_FLOW: server
            VITE_API_URL: ${{ secrets.VITE_API_URL }}
            VITE_COGNITO_DOMAIN: ${{ secrets.VITE_COGNITO_DOMAIN }}
            VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
            VITE_BACKEND_TOKEN_CALLBACK: ${{ secrets.VITE_BACKEND_TOKEN_CALLBACK }}
            VITE_PAYPAL_CLIENT_ID: ${{ secrets.VITE_PAYPAL_CLIENT_ID }}
        run: |
          cd frontend
          corepack enable
          corepack prepare pnpm@10.30.1 --activate
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Sync frontend to S3
        env:
          FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}
        run: |
          aws s3 sync frontend/dist s3://$FRONTEND_BUCKET/ --delete

      - name: Invalidate CloudFront
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
